### PR TITLE
Update build and fix some logged errors

### PR DESCRIPTION
**Pull request by Fourmisain**
I was getting annoyed by these warnings
```
[Worker-Main-4/WARN] (class_1088): Exception loading blockstate definition: surrogate:blockstates/surrogate_block.json: java.io.FileNotFoundException: surrogate:blockstates/surrogate_block.json
[Worker-Main-4/WARN] (class_1088): Exception loading blockstate definition: 'surrogate:blockstates/surrogate_block.json' missing model for variant: 'surrogate:surrogate_block#'
[Worker-Main-4/WARN] (class_1088): Unable to load model: 'surrogate:surrogate_item#inventory' referenced from: surrogate:surrogate_item#inventory: java.io.FileNotFoundException: surrogate:models/item/surrogate_item.json
```
so I added blockstate and model definitions using the `missingo` texture.

I also updated the build to use Loom 0.10, Gradle 7.3 and Minecraft 1.17.1 (no actual code changes).

While at it I added a mod icon and proper description so it'll looks nicer in Mod Menu (and it won't log a missing mod icon warning either).

### CODE REVIEW

**Comment by warjort** [comment]
Thanks for the contribution.

This looks good to me, except...

You haven't really fixed the problem with the warning, because the texture minecraft:missigno doesn't really exist (its a marker used internally by minecraft):
````
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #down in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #up in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #north in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #south in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #west in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #east in surrogate:item/surrogate_item
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #down in surrogate:block/surrogate_block
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #up in surrogate:block/surrogate_block
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #north in surrogate:block/surrogate_block
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #south in surrogate:block/surrogate_block
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #west in surrogate:block/surrogate_block
[15:54:28] [Worker-Main-11/WARN] (Minecraft) Unable to resolve texture reference: #east in surrogate:block/surrogate_block
````

To suppress all the warnings, you should create a real texture that is the purple/black checkerboard and reference that.

**Comment by warjort** [comment]
Some other book keeping requests:

Can you
* Add your name to CONTRIBUTERS
* Update the version to 1.0.1+1.17 and update the CHANGELOG.md with a brief summary of your changes

Finally, can you change the .json files you created to use 4 spaces to indent instead of using tabs.
I know minecraft uses tabs in its files but that can get ugly when different editors use different tab size configurations.

**Comment by Fourmisain** [comment]
> You haven't really fixed the problem with the warning (...) because the texture minecraft:missigno doesn't really exist

Dang, I didn't notice the new warnings because they hid between some other ones.
I also thought it would work because `TextureAtlas.getBasicSpriteInfos()` does actually check for `"missingno"`.

> can you change the .json files you created to use 4 spaces to indent

4, not 2 like `en_us.json` already uses?

**Comment by warjort** [comment]
> 4, not 2 like en_us.json already uses?

2 is kind of the industry standard for json indentation (and other languages like scala), 
but 4 is usually used with java projects (except for eclipse projects which use tabs :-).

The important part is that tabs aren't used so the indentation doesn't look broken if one developer uses tabs for one line 
and another uses spaces.

**Comment by Fourmisain** [comment]
I didn't mean to get into the tabs vs spaces (or 4 spaces vs 2 spaces) argument, just meant that this file
https://github.com/warjort/surrogate/blob/master/src/main/resources/assets/surrogate/lang/en_us.json
uses 2 spaces.

**Comment by warjort** [comment]
That's fine as long as it remains consistent within the same file.

Still get a warning:

[21:38:32] [Worker-Main-12/ERROR] (Minecraft) Using missing texture, unable to load surrogate:textures/block/surrogate.png : java.io.FileNotFoundException: surrogate:textures/block/surrogate.png

The model refers to ````block/surrogate````, but the texture is ````block/surrogate_block.png````

**Comment by Fourmisain** [comment]
> Still get a warning

I clearly need to get some sleep! 😅

Squashed/rewrote some commits, tested it multiple times, I think it should finally be good - third time's the charm?

**Comment by warjort** [comment]
Looks good now.

Thanks again for the contribution.

**Pull request merged**
